### ISSUE TITLE
got wierd email from keymasters

### ISSUE THREAD

**Issue by spanner888** [xinchejian/bouncer#33]
So I got this wierd email .... and I guess maybe it has to do with the work you guys are doing on Bouncer .. or maybe it is a phisihing email..... as the from address is "smtp.mailfrom=keymasters+bncBDONHW5HUUFBBYVTTGXQKGQEZK3PGVY@xinchejian.com"

It is wierd becasue
1. it ONLY talks about confirming my facebook email ... but does not say for what purpose
2. it has my correct email address, but TOTALLY INCORRECT name!

Email subject is "Confirm your Twitter account, incorrect name"
BODY:
Final step...
Confirm your email address to complete your Twitter account @WRONG NAME. It's easy — just click the button below. 

Either way thought you guys need to know!

**Comment by rngadam** [comment]
Can you provide the full headers? It's most likely a forged email. 
<img width="417" alt="screen shot 2015-09-05 at 11 20 13 am" src="https://cloud.githubusercontent.com/assets/538542/9697435/1e6d2842-53c0-11e5-947b-a1686f01ed9f.png">

**Comment by nihaopaul** [comment]
Spam

**Comment by spanner888** [comment]
well yeah .. but you guys AND XCJ members should know that people are abusing XCj in this way!

**Comment by lionello** [comment]
@spanner888 Please send us the email headers so we can take action against this.

**Comment by nihaopaul** [comment]
Not really abuse just opportunistic botnets. But it was a pretty good one.

**Comment by spanner888** [comment]
Delivered-To: some@email.com
Received: by 10.66.161.67 with SMTP id xq3csp237401pab;
        Tue, 1 Sep 2015 19:07:31 -0700 (PDT)
X-Received: by 10.182.105.103 with SMTP id gl7mr9421107obb.46.1441159651406;
        Tue, 01 Sep 2015 19:07:31 -0700 (PDT)
Return-Path: <keymasters+bncBDONHW5HUUFBBYVTTGXQKGQEZK3PGVY@xinchejian.com>
Received: from mail-ob0-f198.google.com (mail-ob0-f198.google.com. [209.85.214.198])
        by mx.google.com with ESMTPS id c3si13286428oem.52.2015.09.01.19.07.30
        for some@email.com
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 01 Sep 2015 19:07:31 -0700 (PDT)
Received-SPF: pass (google.com: domain of keymasters+bncBDONHW5HUUFBBYVTTGXQKGQEZK3PGVY@xinchejian.com designates 209.85.214.198 as permitted sender) client-ip=209.85.214.198;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of keymasters+bncBDONHW5HUUFBBYVTTGXQKGQEZK3PGVY@xinchejian.com designates 209.85.214.198 as permitted sender) smtp.mailfrom=keymasters+bncBDONHW5HUUFBBYVTTGXQKGQEZK3PGVY@xinchejian.com
Received: by obbmm9 with SMTP id mm9sf29697374obb.3
        for some@email.com; Tue, 01 Sep 2015 19:07:30 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:date:from:to:subject:mime-version:content-type
         :feedback-id:precedence:message-id:x-original-sender
         :x-original-authentication-results:mailing-list:list-id
         :x-spam-checked-in-group:list-help:reply-to;
        bh=l6ErZh6D1jQ2uSnB/MnubvpbjN0/cmUXY2DB6rmI3vs=;
        b=IVeMPOhqlI0s0ut+dcpx4igBLVRNw4DCp76fysJPFPgd/PF6+rlvVr4CCq7um5z/Zx
         20MVT+lftop2PzwLhHQkmntNIJJBaobX0w8U7B38msbdqVJPccs+hdSThlGHfbSPmzhW
         aYOt2NC/bkhWeb8dS0kb8T/gC5di2QEgDmwWzrYwqat2ZqtRiFaY9Ts4C0x5dqo1XXcY
         t+VZZh3ooDWcLeTHgYAuCoa1a+Vr0WYAEFsZT55/1M6Ek3oLUszFbpE3jTrzEAbWSz3A
         PDCTdU0LQQpqPwmDmh/yoDXHaFFWdH63Grvpx3seMoZtzVkq1r5qfZxpDqyLn7jqrN0Y
         BYpg==
X-Gm-Message-State: ALoCoQn9xZuJVJ6fkQgYqP1x0YEDV7Qwyvaf6J9sk5vLCz6y6oB0eRFoxWifAl8mo1acznK8RpbK
X-Received: by 10.107.9.208 with SMTP id 77mr39283178ioj.1.1441159650659;
        Tue, 01 Sep 2015 19:07:30 -0700 (PDT)
X-BeenThere: keymasters@xinchejian.com
Received: by 10.182.120.233 with SMTP id lf9ls149385obb.94.gmail; Tue, 01 Sep
 2015 19:07:30 -0700 (PDT)
X-Received: by 10.13.226.22 with SMTP id l22mr30304099ywe.67.1441159650354;
        Tue, 01 Sep 2015 19:07:30 -0700 (PDT)
Received: from spring-chicken-ar.twitter.com (spring-chicken-ar.twitter.com. [199.16.156.157])
        by mx.google.com with ESMTPS id x63si792494yke.26.2015.09.01.19.07.30
        for keymasters@xinchejian.com
        (version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 01 Sep 2015 19:07:30 -0700 (PDT)
Received-SPF: pass (google.com: domain of t068045beda-ece446155-c675a0646e6c407683fcfb7a00ba24b3@bounce.twitter.com designates 199.16.156.157 as permitted sender) client-ip=199.16.156.157;
X-MSFBL: eyJ1Ijoia2V5bWFzdGVyc0B4aW5jaGVqaWFuLmNvbUB1c2IjIzJAMjQ0QDMyOTY2
    MjkyMzJAMEA5ZDVmNzQ1NzJhMDEzNzczOTA1ODg4YzlmYjk0MmZmNjU5M2U3NDUz
    IiwiYiI6ImF0bGEtYXFvLTM5LXNyMS1FdmVyeXRoaW5nLjE3NyIsInIiOiJrZXlt
    YXN0ZXJzQHhpbmNoZWppYW4uY29tIiwiZyI6IkV2ZXJ5dGhpbmcifQ==
Date: Wed, 02 Sep 2015 02:07:30 +0000
From: "'Twitter' via Keymasters" keymasters@xinchejian.com
To: Mitris Beals keymasters@xinchejian.com
Subject: Confirm your Twitter account, Mitris Beals
MIME-Version: 1.0
Content-Type: multipart/alternative; 
    boundary="----=_Part_9433055_71726579.1441159650060"
Feedback-ID: 0040162518f58f41d1f0:104a14252ef4876cc5f9ff3fab597aa4e3e57c597b3932d8fb30:MY:twitterESP
Precedence: list
Message-ID: A0.CF.11675.2E956E55@twitter.com
X-Original-Sender: confirm@twitter.com
X-Original-Authentication-Results: mx.google.com;       spf=pass (google.com:
 domain of t068045beda-ece446155-c675a0646e6c407683fcfb7a00ba24b3@bounce.twitter.com
 designates 199.16.156.157 as permitted sender) smtp.mailfrom=t068045beda-ece446155-c675a0646e6c407683fcfb7a00ba24b3@bounce.twitter.com;
       dkim=pass header.i=@twitter.com;       dmarc=pass (p=REJECT dis=NONE) header.from=twitter.com
Mailing-list: list keymasters@xinchejian.com; contact keymasters+owners@xinchejian.com
List-ID: <keymasters.xinchejian.com>
X-Spam-Checked-In-Group: keymasters@xinchejian.com
X-Google-Group-Id: 754220187258
List-Help: http://support.google.com/a/xinchejian.com/bin/topic.py&topic=25838,
 mailto:keymasters+help@xinchejian.com
X-Original-From: Twitter confirm@twitter.com
Reply-To: Twitter confirm@twitter.com

------=_Part_9433055_71726579.1441159650060
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

**Comment by lionello** [comment]
SPF was working, so this is just a bot that entered "keymasters@xinchejian.com" in the Twitter signup form. There's nothing we can do to prevent that. The reason you got the email is because you're in the keymasters group.
