### ISSUE TITLE
CRON job for membership reminder 

### ISSUE THREAD

**Issue by lionello** [xinchejian/bouncer#7]
Once a day cronjob, send email to everyone with expiring memberships. @Amanda-Maxy will write the email in English and Chinese.

**Comment by Amanda-Maxy** [comment]
done！

**Comment by Amanda-Maxy** [comment]
Dear XinCheJian member,

Your membership with XinCheJian is about to expire today. Please renew your
membership to be able to get into the space.

Thanks for your continuous support!

亲爱的新车间会员，

您在新车间的会员资格即将于今日到期。为了正常使用新车间的空间设施，请为您的会员资格续费！

谢谢您一如既往的支持！

**Comment by Amanda-Maxy** [comment]
新车间会员资格到期提醒
